name: heathcare_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.6
  # flutter_swiper: ^1.1.6
  carousel_slider: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/Image1.jpeg
    - Images/Image2.jpeg
    - Images/Image3.jpeg
    - Images/Image4.jpeg
    - Images/1.png
    - Images/2.png
    - Images/3.png
    - Images/4.png
    - Images/5.png
    - Images/6.png
    - Images/7.png
    - Images/Adho_mukha_svasana.jpg
    - Images/Alcohol.jpg
    - Images/Asthma.jpg
    - Images/Bhandas.jpg
    - Images/Biscuit.jpg
    - Images/Bridge_pose.jpg
    - Images/Camel_pose.jpg
    - Images/cloth_pads.jpg
    - Images/cobbler_pose.jpg
    - Images/Crunches.jpg
    - Images/Crunches1.jpg
    - Images/Dhanurasana.png
    - Images/DirtyClothes.jpg
    - Images/DriedClothes.jpg
    - Images/Fat fod.jpg
    - Images/FriedFood.jpg
    - Images/Fruits.jpg
    - Images/Fruits2.jpg
    - Images/Garland_pose.jpg
    - Images/Glute_lifts.jpg
    - Images/head_to_knee.jpg
    - Images/Heart_attack.jpg
    - Images/Inversions.jpg
    - Images/Inversions1.jpg
    - Images/Iron_rich_food.jpg
    - Images/Legumes.jpg
    - Images/matsyasana.jpg
    - Images/Menstrual_Cramps.jpg
    - Images/Menstrual_cup.jpg
    - Images/MenstrualHygiene.jpg
    - Images/Menstruation.jpg
    - Images/Oil.jpg
    - Images/Osteoporosis.jpg
    - Images/Pelvic_tucks.jpg
    - Images/Pepsi.jpg
    - Images/PMS.jpg
    - Images/Refined_Grains.jpg
    - Images/Running.jpg
    - Images/Salt.jpg
    - Images/Sanitary_pads.jpg
    - Images/Seated_forward_bend.jpg
    - Images/Seated_straddle.jpg
    - Images/Squat_jumps.png
    - Images/Standing_twist.jpg
    - Images/sugar.jpg
    - Images/Tampons.jpg
    - Images/Tofu.jpg
    - Images/Top_taps.jpg
    - Images/Vegetables.jpg
    - Images/Very_strong_asanas.jpg
    - Images/Walking.jpg
    - Images/Water.jpg
    - Images/Yogurt.jpg
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
